// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGpnYRUTr2qG7f8D5Y7sAF_uGE51HmXc',
    appId: '1:1049629390524:web:e2fb3c1c71cfd43b6782b9',
    messagingSenderId: '1049629390524',
    projectId: 'food-app-ui-design',
    authDomain: 'food-app-ui-design.firebaseapp.com',
    storageBucket: 'food-app-ui-design.appspot.com',
    measurementId: 'G-CHR6LH6EDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmBSfY6OtdehyQ6bEraBdupYsW8i7ZH8',
    appId: '1:1049629390524:android:88dbb8b35b01c4c26782b9',
    messagingSenderId: '1049629390524',
    projectId: 'food-app-ui-design',
    storageBucket: 'food-app-ui-design.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiWEXFxhPEsmsu45_MRwH5RVUZRB7SPK4',
    appId: '1:1049629390524:ios:4dd3f9382b5a6dea6782b9',
    messagingSenderId: '1049629390524',
    projectId: 'food-app-ui-design',
    storageBucket: 'food-app-ui-design.appspot.com',
    iosBundleId: 'com.example.foodAppUiDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiWEXFxhPEsmsu45_MRwH5RVUZRB7SPK4',
    appId: '1:1049629390524:ios:4dd3f9382b5a6dea6782b9',
    messagingSenderId: '1049629390524',
    projectId: 'food-app-ui-design',
    storageBucket: 'food-app-ui-design.appspot.com',
    iosBundleId: 'com.example.foodAppUiDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIGpnYRUTr2qG7f8D5Y7sAF_uGE51HmXc',
    appId: '1:1049629390524:web:d3e1754ea52938176782b9',
    messagingSenderId: '1049629390524',
    projectId: 'food-app-ui-design',
    authDomain: 'food-app-ui-design.firebaseapp.com',
    storageBucket: 'food-app-ui-design.appspot.com',
    measurementId: 'G-N307LSSCZY',
  );
}
